# Generated by Django 2.2.6 on 2019-10-30 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191028_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
