# Generated by Django 2.2.6 on 2019-11-06 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191030_1043'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Flavour',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='name',
            new_name='label',
        ),
    ]
